/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://2jdtvw7frbexxclmxgehhezbtm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fnzo6rirffhtfnp24fz4sxpaui",
    "aws_cognito_identity_pool_id": "ap-northeast-1:de87c8f2-175b-4ba8-8467-c44504591928",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_0vjMcuQVh",
    "aws_user_pools_web_client_id": "45mvhinajdrbir22d37pas2ghd",
    "oauth": {}
};


export default awsmobile;
